In [1]:
# working with json and sql files

In [2]:
import pandas as pd
import numpy as np

In [2]:
# reading a json file
df = pd.read_json('train.json')
df.head(3)

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...

In [3]:
# we can also directly read from url 
df = pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')
df.head(3)

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-12,1775952002,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-12,1775952002,0.0395
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-12,1775952002,0.6940

In [6]:
#!pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 270.8 kB/s eta 0:00:42
     - ------------------------------------- 0.5/11.9 MB 270.8 kB/s eta 0:00:42
     -- ------------------------------------ 0.8/11.9 MB 349.5 kB/s eta 0:00:32
     -- ------------------------------------ 0.8/11.9 MB 349.5 kB/s eta 0:00:32
     -- ------------------------------------ 0.8/11.9 MB 349.5 kB/s eta 0:00:32
     -- ------------------------------------ 0.8/11.9 MB 349.5 kB/s eta 0:00:32
     -- ------------------------------------ 0.8/11.9 MB 349.5 kB/s eta 0:00:32
     -- ------------------------------------ 0.8/11.9 MB 349.5 kB/s eta 0:00:32
     -- ------------------------------------ 0.8/11.9 MB 349.5 kB/s eta 0:00:32
     -- ------------------------------------ 0.8/11.9 MB 349.5 kB/s eta 0:00:32
     --- ----------------------------------- 1.0/11.9 MB 237.4 kB/s eta 0:00:46
     --- ----------------------------------- 1.0/11.9 MB 237.4 kB/s eta 0:00:46
     --- ----------------------------------- 1.0/11.9 MB 237.4 kB/s eta 0:00:46
     --- ----------------------------------- 1.0/11.9 MB 237.4 kB/s eta 0:00:46
     --- ----------------------------------- 1.0/11.9 MB 237.4 kB/s eta 0:00:46
     --- ----------------------------------- 1.0/11.9 MB 237.4 kB/s eta 0:00:46
     ---- ---------------------------------- 1.3/11.9 MB 233.8 kB/s eta 0:00:46
     ---- ---------------------------------- 1.3/11.9 MB 233.8 kB/s eta 0:00:46
     ---- ---------------------------------- 1.3/11.9 MB 233.8 kB/s eta 0:00:46
     ---- ---------------------------------- 1.3/11.9 MB 233.8 kB/s eta 0:00:46
     ---- ---------------------------------- 1.3/11.9 MB 233.8 kB/s eta 0:00:46
     ----- --------------------------------- 1.6/11.9 MB 233.7 kB/s eta 0:00:44
     ----- --------------------------------- 1.6/11.9 MB 233.7 kB/s eta 0:00:44
     ----- --------------------------------- 1.6/11.9 MB 233.7 kB/s eta 0:00:44
     ------ -------------------------------- 1.8/11.9 MB 254.2 kB/s eta 0:00:40
     ------ -------------------------------- 1.8/11.9 MB 254.2 kB/s eta 0:00:40
     ------ -------------------------------- 1.8/11.9 MB 254.2 kB/s eta 0:00:40
     ------ -------------------------------- 1.8/11.9 MB 254.2 kB/s eta 0:00:40
     ------ -------------------------------- 2.1/11.9 MB 262.7 kB/s eta 0:00:38
     ------ -------------------------------- 2.1/11.9 MB 262.7 kB/s eta 0:00:38
     ------ -------------------------------- 2.1/11.9 MB 262.7 kB/s eta 0:00:38
     ------ -------------------------------- 2.1/11.9 MB 262.7 kB/s eta 0:00:38
     ------ -------------------------------- 2.1/11.9 MB 262.7 kB/s eta 0:00:38
     ------ -------------------------------- 2.1/11.9 MB 262.7 kB/s eta 0:00:38
     ------ -------------------------------- 2.1/11.9 MB 262.7 kB/s eta 0:00:38
     ------ -------------------------------- 2.1/11.9 MB 262.7 kB/s eta 0:00:38
     ------ -------------------------------- 2.1/11.9 MB 262.7 kB/s eta 0:00:38
     ------- ------------------------------- 2.4/11.9 MB 237.6 kB/s eta 0:00:40
     ------- ------------------------------- 2.4/11.9 MB 237.6 kB/s eta 0:00:40
     ------- ------------------------------- 2.4/11.9 MB 237.6 kB/s eta 0:00:40
     ------- ------------------------------- 2.4/11.9 MB 237.6 kB/s eta 0:00:40
     ------- ------------------------------- 2.4/11.9 MB 237.6 kB/s eta 0:00:40
     ------- ------------------------------- 2.4/11.9 MB 237.6 kB/s eta 0:00:40
     ------- ------------------------------- 2.4/11.9 MB 237.6 kB/s eta 0:00:40
     -------- ------------------------------ 2.6/11.9 MB 228.1 kB/s eta 0:00:41
     -------- ------------------------------ 2.6/11.9 MB 228.1 kB/s eta 0:00:41
     -------- ------------------------------ 2.6/11.9 MB 228.1 kB/s eta 0:00:41
     -------- ------------------------------ 2.6/11.9 MB 228.1 kB/s eta 0:00:41
     -------- ------------------------------ 2.6/11.9 MB 228.1 kB/s eta 0:00:41
     --------- ----------------------------- 2.9/11.9 MB 230.5 kB/s eta 0:00:39
     --------- ----------------------------- 2.9/11.9 MB 230.5 kB/s eta 0:00:39
     --------- ----------------------------- 2.9/11.9 MB 230.5 kB/s eta 0:00:39
     --------- ----------------------------- 2.9/11.9 MB 230.5 kB/s eta 0:00:39
     --------- ----------------------------- 2.9/11.9 MB 230.5 kB/s eta 0:00:39
     ---------- ---------------------------- 3.1/11.9 MB 231.0 kB/s eta 0:00:38
     ---------- ---------------------------- 3.1/11.9 MB 231.0 kB/s eta 0:00:38
     ---------- ---------------------------- 3.1/11.9 MB 231.0 kB/s eta 0:00:38
     ----------- --------------------------- 3.4/11.9 MB 239.7 kB/s eta 0:00:36
     ----------- --------------------------- 3.4/11.9 MB 239.7 kB/s eta 0:00:36
     ----------- --------------------------- 3.4/11.9 MB 239.7 kB/s eta 0:00:36
     ----------- --------------------------- 3.4/11.9 MB 239.7 kB/s eta 0:00:36
     ----------- --------------------------- 3.4/11.9 MB 239.7 kB/s eta 0:00:36
     ----------- --------------------------- 3.4/11.9 MB 239.7 kB/s eta 0:00:36
     ------------ -------------------------- 3.7/11.9 MB 236.3 kB/s eta 0:00:35
     ------------ -------------------------- 3.7/11.9 MB 236.3 kB/s eta 0:00:35
     ------------ -------------------------- 3.7/11.9 MB 236.3 kB/s eta 0:00:35
     ------------ -------------------------- 3.7/11.9 MB 236.3 kB/s eta 0:00:35
     ------------ -------------------------- 3.9/11.9 MB 241.2 kB/s eta 0:00:33
     ------------ -------------------------- 3.9/11.9 MB 241.2 kB/s eta 0:00:33
     ------------ -------------------------- 3.9/11.9 MB 241.2 kB/s eta 0:00:33
     ------------ -------------------------- 3.9/11.9 MB 241.2 kB/s eta 0:00:33
     ------------ -------------------------- 3.9/11.9 MB 241.2 kB/s eta 0:00:33
     ------------ -------------------------- 3.9/11.9 MB 241.2 kB/s eta 0:00:33
     ------------ -------------------------- 3.9/11.9 MB 241.2 kB/s eta 0:00:33
     ------------- ------------------------- 4.2/11.9 MB 237.0 kB/s eta 0:00:33
     ------------- ------------------------- 4.2/11.9 MB 237.0 kB/s eta 0:00:33
     ------------- ------------------------- 4.2/11.9 MB 237.0 kB/s eta 0:00:33
     ------------- ------------------------- 4.2/11.9 MB 237.0 kB/s eta 0:00:33
     ------------- ------------------------- 4.2/11.9 MB 237.0 kB/s eta 0:00:33
     -------------- ------------------------ 4.5/11.9 MB 237.4 kB/s eta 0:00:32
     -------------- ------------------------ 4.5/11.9 MB 237.4 kB/s eta 0:00:32
     -------------- ------------------------ 4.5/11.9 MB 237.4 kB/s eta 0:00:32
     -------------- ------------------------ 4.5/11.9 MB 237.4 kB/s eta 0:00:32
     -------------- ------------------------ 4.5/11.9 MB 237.4 kB/s eta 0:00:32
     -------------- ------------------------ 4.5/11.9 MB 237.4 kB/s eta 0:00:32
     -------------- ------------------------ 4.5/11.9 MB 237.4 kB/s eta 0:00:32
     -------------- ------------------------ 4.5/11.9 MB 237.4 kB/s eta 0:00:32
     -------------- ------------------------ 4.5/11.9 MB 237.4 kB/s eta 0:00:32
     --------------- ----------------------- 4.7/11.9 MB 227.5 kB/s eta 0:00:32
     --------------- ----------------------- 4.7/11.9 MB 227.5 kB/s eta 0:00:32
     --------------- ----------------------- 4.7/11.9 MB 227.5 kB/s eta 0:00:32
     ---------------- ---------------------- 5.0/11.9 MB 232.7 kB/s eta 0:00:30
     ---------------- ---------------------- 5.0/11.9 MB 232.7 kB/s eta 0:00:30
     ---------------- ---------------------- 5.0/11.9 MB 232.7 kB/s eta 0:00:30
     ---------------- ---------------------- 5.0/11.9 MB 232.7 kB/s eta 0:00:30
     ---------------- ---------------------- 5.0/11.9 MB 232.7 kB/s eta 0:00:30
     ---------------- ---------------------- 5.0/11.9 MB 232.7 kB/s eta 0:00:30
     ----------------- --------------------- 5.2/11.9 MB 231.7 kB/s eta 0:00:29
     ----------------- --------------------- 5.2/11.9 MB 231.7 kB/s eta 0:00:29
     ----------------- --------------------- 5.2/11.9 MB 231.7 kB/s eta 0:00:29
     ----------------- --------------------- 5.2/11.9 MB 231.7 kB/s eta 0:00:29
     ----------------- --------------------- 5.2/11.9 MB 231.7 kB/s eta 0:00:29
     ----------------- --------------------- 5.2/11.9 MB 231.7 kB/s eta 0:00:29
     ------------------ -------------------- 5.5/11.9 MB 229.0 kB/s eta 0:00:28
     ------------------ -------------------- 5.5/11.9 MB 229.0 kB/s eta 0:00:28
     ------------------ -------------------- 5.5/11.9 MB 229.0 kB/s eta 0:00:28
     ------------------ -------------------- 5.5/11.9 MB 229.0 kB/s eta 0:00:28
     ------------------ -------------------- 5.5/11.9 MB 229.0 kB/s eta 0:00:28
     ------------------ -------------------- 5.5/11.9 MB 229.0 kB/s eta 0:00:28
     ------------------ -------------------- 5.8/11.9 MB 229.1 kB/s eta 0:00:27
     ------------------ -------------------- 5.8/11.9 MB 229.1 kB/s eta 0:00:27
     ------------------- ------------------- 6.0/11.9 MB 234.8 kB/s eta 0:00:25
     ------------------- ------------------- 6.0/11.9 MB 234.8 kB/s eta 0:00:25
     -------------------- ------------------ 6.3/11.9 MB 241.2 kB/s eta 0:00:24
     -------------------- ------------------ 6.3/11.9 MB 241.2 kB/s eta 0:00:24
     -------------------- ------------------ 6.3/11.9 MB 241.2 kB/s eta 0:00:24
     -------------------- ------------------ 6.3/11.9 MB 241.2 kB/s eta 0:00:24
     --------------------- ----------------- 6.6/11.9 MB 244.0 kB/s eta 0:00:22
     --------------------- ----------------- 6.6/11.9 MB 244.0 kB/s eta 0:00:22
     --------------------- ----------------- 6.6/11.9 MB 244.0 kB/s eta 0:00:22
     --------------------- ----------------- 6.6/11.9 MB 244.0 kB/s eta 0:00:22
     --------------------- ----------------- 6.6/11.9 MB 244.0 kB/s eta 0:00:22
     ---------------------- ---------------- 6.8/11.9 MB 243.0 kB/s eta 0:00:21
     ---------------------- ---------------- 6.8/11.9 MB 243.0 kB/s eta 0:00:21
     ---------------------- ---------------- 6.8/11.9 MB 243.0 kB/s eta 0:00:21
     ----------------------- --------------- 7.1/11.9 MB 247.3 kB/s eta 0:00:20
     ----------------------- --------------- 7.1/11.9 MB 247.3 kB/s eta 0:00:20
     ----------------------- --------------- 7.1/11.9 MB 247.3 kB/s eta 0:00:20
     ----------------------- --------------- 7.1/11.9 MB 247.3 kB/s eta 0:00:20
     ----------------------- --------------- 7.1/11.9 MB 247.3 kB/s eta 0:00:20
     ----------------------- --------------- 7.1/11.9 MB 247.3 kB/s eta 0:00:20
     ----------------------- --------------- 7.1/11.9 MB 247.3 kB/s eta 0:00:20
     ------------------------ -------------- 7.3/11.9 MB 243.9 kB/s eta 0:00:19
     ------------------------ -------------- 7.3/11.9 MB 243.9 kB/s eta 0:00:19
     ------------------------ -------------- 7.3/11.9 MB 243.9 kB/s eta 0:00:19
     ------------------------ -------------- 7.3/11.9 MB 243.9 kB/s eta 0:00:19
     ------------------------ -------------- 7.3/11.9 MB 243.9 kB/s eta 0:00:19
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.6/11.9 MB 243.3 kB/s eta 0:00:18
     ------------------------- ------------- 7.9/11.9 MB 233.4 kB/s eta 0:00:18
     ------------------------- ------------- 7.9/11.9 MB 233.4 kB/s eta 0:00:18
     ------------------------- ------------- 7.9/11.9 MB 233.4 kB/s eta 0:00:18
     ------------------------- ------------- 7.9/11.9 MB 233.4 kB/s eta 0:00:18
     ------------------------- ------------- 7.9/11.9 MB 233.4 kB/s eta 0:00:18
     ------------------------- ------------- 7.9/11.9 MB 233.4 kB/s eta 0:00:18
     -------------------------- ------------ 8.1/11.9 MB 233.3 kB/s eta 0:00:16
     -------------------------- ------------ 8.1/11.9 MB 233.3 kB/s eta 0:00:16
     -------------------------- ------------ 8.1/11.9 MB 233.3 kB/s eta 0:00:16
     --------------------------- ----------- 8.4/11.9 MB 236.4 kB/s eta 0:00:15
     --------------------------- ----------- 8.4/11.9 MB 236.4 kB/s eta 0:00:15
     --------------------------- ----------- 8.4/11.9 MB 236.4 kB/s eta 0:00:15
     --------------------------- ----------- 8.4/11.9 MB 236.4 kB/s eta 0:00:15
     --------------------------- ----------- 8.4/11.9 MB 236.4 kB/s eta 0:00:15
     ---------------------------- ---------- 8.7/11.9 MB 236.4 kB/s eta 0:00:14
     ---------------------------- ---------- 8.7/11.9 MB 236.4 kB/s eta 0:00:14
     ---------------------------- ---------- 8.7/11.9 MB 236.4 kB/s eta 0:00:14
     ---------------------------- ---------- 8.7/11.9 MB 236.4 kB/s eta 0:00:14
     ---------------------------- ---------- 8.7/11.9 MB 236.4 kB/s eta 0:00:14
     ----------------------------- --------- 8.9/11.9 MB 230.6 kB/s eta 0:00:13
     ----------------------------- --------- 8.9/11.9 MB 230.6 kB/s eta 0:00:13
     ----------------------------- --------- 8.9/11.9 MB 230.6 kB/s eta 0:00:13
     ----------------------------- --------- 8.9/11.9 MB 230.6 kB/s eta 0:00:13
     ----------------------------- --------- 8.9/11.9 MB 230.6 kB/s eta 0:00:13
     ----------------------------- --------- 8.9/11.9 MB 230.6 kB/s eta 0:00:13
     ------------------------------ -------- 9.2/11.9 MB 234.6 kB/s eta 0:00:12
     ------------------------------ -------- 9.2/11.9 MB 234.6 kB/s eta 0:00:12
     ------------------------------ -------- 9.2/11.9 MB 234.6 kB/s eta 0:00:12
     ------------------------------ -------- 9.2/11.9 MB 234.6 kB/s eta 0:00:12
     ------------------------------ -------- 9.2/11.9 MB 234.6 kB/s eta 0:00:12
     ------------------------------- ------- 9.4/11.9 MB 238.9 kB/s eta 0:00:11
     ------------------------------- ------- 9.4/11.9 MB 238.9 kB/s eta 0:00:11
     ------------------------------- ------- 9.4/11.9 MB 238.9 kB/s eta 0:00:11
     ------------------------------- ------- 9.4/11.9 MB 238.9 kB/s eta 0:00:11
     ------------------------------- ------- 9.7/11.9 MB 241.1 kB/s eta 0:00:09
     ------------------------------- ------- 9.7/11.9 MB 241.1 kB/s eta 0:00:09
     ------------------------------- ------- 9.7/11.9 MB 241.1 kB/s eta 0:00:09
     ------------------------------- ------- 9.7/11.9 MB 241.1 kB/s eta 0:00:09
     ------------------------------- ------- 9.7/11.9 MB 241.1 kB/s eta 0:00:09
     ------------------------------- ------- 9.7/11.9 MB 241.1 kB/s eta 0:00:09
     ------------------------------- ------ 10.0/11.9 MB 239.8 kB/s eta 0:00:08
     ------------------------------- ------ 10.0/11.9 MB 239.8 kB/s eta 0:00:08
     ------------------------------- ------ 10.0/11.9 MB 239.8 kB/s eta 0:00:08
     ------------------------------- ------ 10.0/11.9 MB 239.8 kB/s eta 0:00:08
     ------------------------------- ------ 10.0/11.9 MB 239.8 kB/s eta 0:00:08
     ------------------------------- ------ 10.0/11.9 MB 239.8 kB/s eta 0:00:08
     -------------------------------- ----- 10.2/11.9 MB 238.5 kB/s eta 0:00:07
     -------------------------------- ----- 10.2/11.9 MB 238.5 kB/s eta 0:00:07
     -------------------------------- ----- 10.2/11.9 MB 238.5 kB/s eta 0:00:07
     -------------------------------- ----- 10.2/11.9 MB 238.5 kB/s eta 0:00:07
     -------------------------------- ----- 10.2/11.9 MB 238.5 kB/s eta 0:00:07
     -------------------------------- ----- 10.2/11.9 MB 238.5 kB/s eta 0:00:07
     -------------------------------- ----- 10.2/11.9 MB 238.5 kB/s eta 0:00:07
     --------------------------------- ---- 10.5/11.9 MB 233.1 kB/s eta 0:00:06
     --------------------------------- ---- 10.5/11.9 MB 233.1 kB/s eta 0:00:06
     --------------------------------- ---- 10.5/11.9 MB 233.1 kB/s eta 0:00:06
     --------------------------------- ---- 10.5/11.9 MB 233.1 kB/s eta 0:00:06
     --------------------------------- ---- 10.5/11.9 MB 233.1 kB/s eta 0:00:06
     --------------------------------- ---- 10.5/11.9 MB 233.1 kB/s eta 0:00:06
     --------------------------------- ---- 10.5/11.9 MB 233.1 kB/s eta 0:00:06
     ---------------------------------- --- 10.7/11.9 MB 228.3 kB/s eta 0:00:05
     ---------------------------------- --- 10.7/11.9 MB 228.3 kB/s eta 0:00:05
     ---------------------------------- --- 10.7/11.9 MB 228.3 kB/s eta 0:00:05
     ---------------------------------- --- 10.7/11.9 MB 228.3 kB/s eta 0:00:05
     ---------------------------------- --- 10.7/11.9 MB 228.3 kB/s eta 0:00:05
     ---------------------------------- --- 10.7/11.9 MB 228.3 kB/s eta 0:00:05
     ---------------------------------- --- 10.7/11.9 MB 228.3 kB/s eta 0:00:05
     ---------------------------------- --- 10.7/11.9 MB 228.3 kB/s eta 0:00:05
     ----------------------------------- -- 11.0/11.9 MB 224.4 kB/s eta 0:00:04
     ----------------------------------- -- 11.0/11.9 MB 224.4 kB/s eta 0:00:04
     ----------------------------------- -- 11.0/11.9 MB 224.4 kB/s eta 0:00:04
     ----------------------------------- -- 11.0/11.9 MB 224.4 kB/s eta 0:00:04
     ------------------------------------ - 11.3/11.9 MB 227.5 kB/s eta 0:00:03
     ------------------------------------ - 11.3/11.9 MB 227.5 kB/s eta 0:00:03
     ------------------------------------ - 11.3/11.9 MB 227.5 kB/s eta 0:00:03
     ------------------------------------ - 11.3/11.9 MB 227.5 kB/s eta 0:00:03
     ------------------------------------ - 11.3/11.9 MB 227.5 kB/s eta 0:00:03
     ------------------------------------ - 11.3/11.9 MB 227.5 kB/s eta 0:00:03
     ------------------------------------ - 11.3/11.9 MB 227.5 kB/s eta 0:00:03
     ------------------------------------ - 11.3/11.9 MB 227.5 kB/s eta 0:00:03
     ------------------------------------ - 11.3/11.9 MB 227.5 kB/s eta 0:00:03
     ------------------------------------ - 11.5/11.9 MB 223.0 kB/s eta 0:00:02
     ------------------------------------ - 11.5/11.9 MB 223.0 kB/s eta 0:00:02
     ------------------------------------ - 11.5/11.9 MB 223.0 kB/s eta 0:00:02
     ------------------------------------ - 11.5/11.9 MB 223.0 kB/s eta 0:00:02
     ------------------------------------ - 11.5/11.9 MB 223.0 kB/s eta 0:00:02
     ------------------------------------ - 11.5/11.9 MB 223.0 kB/s eta 0:00:02
     -------------------------------------  11.8/11.9 MB 223.5 kB/s eta 0:00:01
     -------------------------------------  11.8/11.9 MB 223.5 kB/s eta 0:00:01
     -------------------------------------- 11.9/11.9 MB 221.5 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started

  DEPRECATION: Building 'mysql.connector' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'mysql.connector'. Discussion can be found at https://github.com/pypa/pip/issues/6334

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
#!python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\users\gpava\appdata\roaming\python\python312\site-packages (25.1.1)
Collecting pip
  Downloading pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------- ---------------------------- 0.5/1.8 MB 118.1 kB/s eta 0:00:11
   ----------------- ---------------------- 0.8/1.8 MB 121.1 kB/s eta 0:00:09
   ----------------- ---------------------- 0.8/1.8 MB 121.1 kB/s eta 0:00:09
   ----------------- ---------------------- 0.8/1.8 MB 121.1 kB/s eta 0:00:09
   ----------------- ---------------------- 0.8/1.8 MB 121.1 kB/s eta 0:00:09
   ----------------------- ---------------- 1.0/1.8 MB 149.8 kB/s eta 0:00:05
   ----------------------- ---------------- 1.0/1.8 MB 149.8 kB/s eta 0:00:05
   ----------------------- ---------------- 1.0/1.8 MB 149.8 kB/s eta 0:00:05
   ----------------------- ---------------- 1.0/1.8 MB 149.8 kB/s eta 0:00:05
   ----------------------- ---------------- 1.0/1.8 MB 149.8 kB/s eta 0:00:05
   ----------------------------- ---------- 1.3/1.8 MB 165.3 kB/s eta 0:00:03
   ----------------------------- ---------- 1.3/1.8 MB 165.3 kB/s eta 0:00:03
   ----------------------------- ---------- 1.3/1.8 MB 165.3 kB/s eta 0:00:03
   ----------------------------- ---------- 1.3/1.8 MB 165.3 kB/s eta 0:00:03
   ----------------------------- ---------- 1.3/1.8 MB 165.3 kB/s eta 0:00:03
   ----------------------------- ---------- 1.3/1.8 MB 165.3 kB/s eta 0:00:03
   ----------------------------- ---------- 1.3/1.8 MB 165.3 kB/s eta 0:00:03
   ----------------------------- ---------- 1.3/1.8 MB 165.3 kB/s eta 0:00:03
   ----------------------------------- ---- 1.6/1.8 MB 163.2 kB/s eta 0:00:02
   ----------------------------------- ---- 1.6/1.8 MB 163.2 kB/s eta 0:00:02
   ----------------------------------- ---- 1.6/1.8 MB 163.2 kB/s eta 0:00:02
   ----------------------------------- ---- 1.6/1.8 MB 163.2 kB/s eta 0:00:02
   ---------------------------------------- 1.8/1.8 MB 172.2 kB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.1.1
    Uninstalling pip-25.1.1:
      Successfully uninstalled pip-25.1.1
Successfully installed pip-26.0.1

In [9]:
#import mysql.connector

ModuleNotFoundError: No module named 'mysql'

In [10]:
#fixin above issue
#import sys
#sys.executable

'C:\\Users\\gpava\\anaconda3\\python.exe'

In [11]:
#!{sys.executable} -m pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp311-cp311-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB 145.2 kB/s eta 0:01:54
   ---------------------------------------- 0.0/16.5 MB 145.2 kB/s eta 0:01:54
   ---------------------------------------- 0.1/16.5 MB 348.6 kB/s eta 0:00:48
   ---------------------------------------- 0.2/16.5 MB 482.7 kB/s eta 0:00:34
   ---------------------------------------- 0.2/16.5 MB 593.2 kB/s eta 0:00:28
    --------------------------------------- 0.2/16.5 MB 550.0 kB/s eta 0:00:30
    --------------------------------------- 0.2/16.5 MB 550.0 kB/s eta 0:00:30
    --------------------------------------- 0.2/16.5 MB 514.3 kB/s eta 0:00:32
    --------------------------------------- 0.3/16.5 MB 491.5 kB/s eta 0:00:34
    --------------------------------------- 0.3/16.5 MB 486.7 kB/s eta 0:00:34
    --------------------------------------- 0.3/16.5 MB 486.8 kB/s eta 0:00:34
    --------------------------------------- 0.3/16.5 MB 491.5 kB/s eta 0:00:33
    --------------------------------------- 0.4/16.5 MB 506.0 kB/s eta 0:00:32
    --------------------------------------- 0.4/16.5 MB 498.5 kB/s eta 0:00:33
    --------------------------------------- 0.4/16.5 MB 494.6 kB/s eta 0:00:33
    --------------------------------------- 0.4/16.5 MB 470.0 kB/s eta 0:00:35
    --------------------------------------- 0.4/16.5 MB 470.0 kB/s eta 0:00:35
   - -------------------------------------- 0.4/16.5 MB 451.6 kB/s eta 0:00:36
   - -------------------------------------- 0.4/16.5 MB 426.2 kB/s eta 0:00:38
   - -------------------------------------- 0.4/16.5 MB 436.6 kB/s eta 0:00:37
   - -------------------------------------- 0.5/16.5 MB 414.2 kB/s eta 0:00:39
   - -------------------------------------- 0.5/16.5 MB 409.6 kB/s eta 0:00:40
   - -------------------------------------- 0.5/16.5 MB 409.6 kB/s eta 0:00:40
   - -------------------------------------- 0.5/16.5 MB 401.9 kB/s eta 0:00:40
   - -------------------------------------- 0.5/16.5 MB 393.2 kB/s eta 0:00:41
   - -------------------------------------- 0.5/16.5 MB 389.9 kB/s eta 0:00:42
   - -------------------------------------- 0.5/16.5 MB 384.0 kB/s eta 0:00:42
   - -------------------------------------- 0.6/16.5 MB 390.2 kB/s eta 0:00:41
   - -------------------------------------- 0.6/16.5 MB 384.5 kB/s eta 0:00:42
   - -------------------------------------- 0.6/16.5 MB 382.3 kB/s eta 0:00:42
   - -------------------------------------- 0.6/16.5 MB 382.3 kB/s eta 0:00:42
   - -------------------------------------- 0.6/16.5 MB 380.0 kB/s eta 0:00:42
   - -------------------------------------- 0.6/16.5 MB 380.0 kB/s eta 0:00:42
   - -------------------------------------- 0.6/16.5 MB 357.9 kB/s eta 0:00:45
   - -------------------------------------- 0.6/16.5 MB 363.4 kB/s eta 0:00:44
   - -------------------------------------- 0.6/16.5 MB 363.4 kB/s eta 0:00:44
   - -------------------------------------- 0.6/16.5 MB 353.3 kB/s eta 0:00:45
   - -------------------------------------- 0.7/16.5 MB 360.4 kB/s eta 0:00:44
   - -------------------------------------- 0.7/16.5 MB 359.8 kB/s eta 0:00:44
   - -------------------------------------- 0.7/16.5 MB 364.0 kB/s eta 0:00:44
   - -------------------------------------- 0.7/16.5 MB 365.7 kB/s eta 0:00:44
   - -------------------------------------- 0.8/16.5 MB 369.6 kB/s eta 0:00:43
   - -------------------------------------- 0.8/16.5 MB 373.7 kB/s eta 0:00:43
   - -------------------------------------- 0.8/16.5 MB 370.3 kB/s eta 0:00:43
   -- ------------------------------------- 0.8/16.5 MB 371.9 kB/s eta 0:00:43
   -- ------------------------------------- 0.8/16.5 MB 375.7 kB/s eta 0:00:42
   -- ------------------------------------- 0.8/16.5 MB 375.7 kB/s eta 0:00:42
   -- ------------------------------------- 0.9/16.5 MB 365.1 kB/s eta 0:00:43
   -- ------------------------------------- 0.9/16.5 MB 365.9 kB/s eta 0:00:43
   -- ------------------------------------- 0.9/16.5 MB 375.7 kB/s eta 0:00:42
   -- ------------------------------------- 1.0/16.5 MB 380.9 kB/s eta 0:00:41
   -- ------------------------------------- 1.0/16.5 MB 380.9 kB/s eta 0:00:41
   -- ------------------------------------- 1.0/16.5 MB 375.6 kB/s eta 0:00:42
   -- ------------------------------------- 1.0/16.5 MB 374.5 kB/s eta 0:00:42
   -- ------------------------------------- 1.0/16.5 MB 377.1 kB/s eta 0:00:42
   -- ------------------------------------- 1.0/16.5 MB 382.6 kB/s eta 0:00:41
   -- ------------------------------------- 1.0/16.5 MB 382.6 kB/s eta 0:00:41
   -- ------------------------------------- 1.0/16.5 MB 382.6 kB/s eta 0:00:41
   -- ------------------------------------- 1.0/16.5 MB 382.6 kB/s eta 0:00:41
   -- ------------------------------------- 1.0/16.5 MB 382.6 kB/s eta 0:00:41
   -- ------------------------------------- 1.1/16.5 MB 355.5 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 355.0 kB/s eta 0:00:44
   -- ------------------------------------- 1.1/16.5 MB 283.6 kB/s eta 0:00:55
   -- ------------------------------------- 1.1/16.5 MB 283.6 kB/s eta 0:00:55
   -- ------------------------------------- 1.1/16.5 MB 283.6 kB/s eta 0:00:55
   -- ------------------------------------- 1.1/16.5 MB 283.6 kB/s eta 0:00:55
   -- ------------------------------------- 1.1/16.5 MB 275.0 kB/s eta 0:00:57
   -- ------------------------------------- 1.1/16.5 MB 275.8 kB/s eta 0:00:56
   -- ------------------------------------- 1.2/16.5 MB 284.0 kB/s eta 0:00:54
   -- ------------------------------------- 1.2/16.5 MB 285.5 kB/s eta 0:00:54
   -- ------------------------------------- 1.2/16.5 MB 288.5 kB/s eta 0:00:54
   --- ------------------------------------ 1.2/16.5 MB 291.3 kB/s eta 0:00:53
   --- ------------------------------------ 1.3/16.5 MB 292.8 kB/s eta 0:00:53
   --- ------------------------------------ 1.3/16.5 MB 291.0 kB/s eta 0:00:53
   --- ------------------------------------ 1.3/16.5 MB 292.6 kB/s eta 0:00:53
   --- ------------------------------------ 1.3/16.5 MB 292.8 kB/s eta 0:00:52
   --- ------------------------------------ 1.3/16.5 MB 293.3 kB/s eta 0:00:52
   --- ------------------------------------ 1.3/16.5 MB 293.3 kB/s eta 0:00:52
   --- ------------------------------------ 1.4/16.5 MB 294.0 kB/s eta 0:00:52
   --- ------------------------------------ 1.4/16.5 MB 296.5 kB/s eta 0:00:52
   --- ------------------------------------ 1.4/16.5 MB 299.0 kB/s eta 0:00:51
   --- ------------------------------------ 1.4/16.5 MB 302.6 kB/s eta 0:00:50
   --- ------------------------------------ 1.5/16.5 MB 311.4 kB/s eta 0:00:49
   --- ------------------------------------ 1.5/16.5 MB 313.8 kB/s eta 0:00:48
   --- ------------------------------------ 1.5/16.5 MB 317.0 kB/s eta 0:00:48
   --- ------------------------------------ 1.5/16.5 MB 317.0 kB/s eta 0:00:48
   --- ------------------------------------ 1.5/16.5 MB 313.0 kB/s eta 0:00:48
   --- ------------------------------------ 1.6/16.5 MB 313.2 kB/s eta 0:00:48
   --- ------------------------------------ 1.6/16.5 MB 315.4 kB/s eta 0:00:48
   --- ------------------------------------ 1.6/16.5 MB 315.4 kB/s eta 0:00:48
   --- ------------------------------------ 1.6/16.5 MB 316.6 kB/s eta 0:00:48
   --- ------------------------------------ 1.6/16.5 MB 319.7 kB/s eta 0:00:47
   --- ------------------------------------ 1.6/16.5 MB 319.7 kB/s eta 0:00:47
   ---- ----------------------------------- 1.7/16.5 MB 319.8 kB/s eta 0:00:47
   ---- ----------------------------------- 1.7/16.5 MB 318.8 kB/s eta 0:00:47
   ---- ----------------------------------- 1.7/16.5 MB 319.9 kB/s eta 0:00:47
   ---- ----------------------------------- 1.7/16.5 MB 319.9 kB/s eta 0:00:47
   ---- ----------------------------------- 1.7/16.5 MB 315.3 kB/s eta 0:00:47
   ---- ----------------------------------- 1.7/16.5 MB 315.5 kB/s eta 0:00:47
   ---- ----------------------------------- 1.7/16.5 MB 315.5 kB/s eta 0:00:47
   ---- ----------------------------------- 1.8/16.5 MB 314.7 kB/s eta 0:00:47
   ---- ----------------------------------- 1.8/16.5 MB 314.7 kB/s eta 0:00:47
   ---- ----------------------------------- 1.8/16.5 MB 312.1 kB/s eta 0:00:48
   ---- ----------------------------------- 1.8/16.5 MB 312.3 kB/s eta 0:00:48
   ---- ----------------------------------- 1.8/16.5 MB 314.3 kB/s eta 0:00:47
   ---- ----------------------------------- 1.8/16.5 MB 317.0 kB/s eta 0:00:47
   ---- ----------------------------------- 1.9/16.5 MB 319.8 kB/s eta 0:00:46
   ---- ----------------------------------- 1.9/16.5 MB 320.7 kB/s eta 0:00:46
   ---- ----------------------------------- 1.9/16.5 MB 323.3 kB/s eta 0:00:46
   ---- ----------------------------------- 1.9/16.5 MB 324.2 kB/s eta 0:00:45
   ---- ----------------------------------- 2.0/16.5 MB 323.4 kB/s eta 0:00:46
   ---- ----------------------------------- 2.0/16.5 MB 323.4 kB/s eta 0:00:46
   ---- ----------------------------------- 2.0/16.5 MB 323.5 kB/s eta 0:00:45
   ---- ----------------------------------- 2.0/16.5 MB 323.5 kB/s eta 0:00:45
   ---- ----------------------------------- 2.0/16.5 MB 323.5 kB/s eta 0:00:45
   ---- ----------------------------------- 2.0/16.5 MB 321.1 kB/s eta 0:00:46
   ---- ----------------------------------- 2.0/16.5 MB 321.1 kB/s eta 0:00:46
   ---- ----------------------------------- 2.0/16.5 MB 321.1 kB/s eta 0:00:46
   ---- ----------------------------------- 2.0/16.5 MB 318.8 kB/s eta 0:00:46
   ---- ----------------------------------- 2.1/16.5 MB 318.1 kB/s eta 0:00:46
   ---- ----------------------------------- 2.1/16.5 MB 318.1 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 319.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 316.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.6 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 316.9 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.1/16.5 MB 317.0 kB/s eta 0:00:46
   ----- ---------------------------------- 2.2/16.5 MB 282.4 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 282.8 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 283.7 kB/s eta 0:00:51
   ----- ---------------------------------- 2.2/16.5 MB 260.2 kB/s eta 0:00:55
   ----- ---------------------------------- 2.2/16.5 MB 260.2 kB/s eta 0:00:55
   ----- ---------------------------------- 2.2/16.5 MB 260.2 kB/s eta 0:00:55
   ----- ---------------------------------- 2.2/16.5 MB 260.2 kB/s eta 0:00:55
   ----- ---------------------------------- 2.2/16.5 MB 260.2 kB/s eta 0:00:55
   ----- ---------------------------------- 2.2/16.5 MB 260.2 kB/s eta 0:00:55
   ----- ---------------------------------- 2.2/16.5 MB 260.2 kB/s eta 0:00:55
   ----- ---------------------------------- 2.2/16.5 MB 260.2 kB/s eta 0:00:55
   ----- ---------------------------------- 2.2/16.5 MB 250.8 kB/s eta 0:00:57
   ----- ---------------------------------- 2.2/16.5 MB 250.8 kB/s eta 0:00:57
   ----- ---------------------------------- 2.3/16.5 MB 250.9 kB/s eta 0:00:57
   ----- ---------------------------------- 2.3/16.5 MB 251.0 kB/s eta 0:00:57
   ----- ---------------------------------- 2.3/16.5 MB 250.8 kB/s eta 0:00:57
   ----- ---------------------------------- 2.3/16.5 MB 252.2 kB/s eta 0:00:57
   ----- ---------------------------------- 2.3/16.5 MB 252.1 kB/s eta 0:00:57
   ----- ---------------------------------- 2.3/16.5 MB 252.6 kB/s eta 0:00:57
   ----- ---------------------------------- 2.3/16.5 MB 252.6 kB/s eta 0:00:57
   ----- ---------------------------------- 2.4/16.5 MB 252.6 kB/s eta 0:00:57
   ----- ---------------------------------- 2.4/16.5 MB 254.2 kB/s eta 0:00:56
   ----- ---------------------------------- 2.4/16.5 MB 258.0 kB/s eta 0:00:55
   ----- ---------------------------------- 2.5/16.5 MB 260.4 kB/s eta 0:00:54
   ------ --------------------------------- 2.5/16.5 MB 260.6 kB/s eta 0:00:54
   ------ --------------------------------- 2.5/16.5 MB 261.5 kB/s eta 0:00:54
   ------ --------------------------------- 2.5/16.5 MB 261.5 kB/s eta 0:00:54
   ------ --------------------------------- 2.5/16.5 MB 261.5 kB/s eta 0:00:54
   ------ --------------------------------- 2.5/16.5 MB 260.9 kB/s eta 0:00:54
   ------ --------------------------------- 2.5/16.5 MB 261.7 kB/s eta 0:00:54
   ------ --------------------------------- 2.6/16.5 MB 261.1 kB/s eta 0:00:54
   ------ --------------------------------- 2.6/16.5 MB 262.3 kB/s eta 0:00:54
   ------ --------------------------------- 2.6/16.5 MB 263.2 kB/s eta 0:00:53
   ------ --------------------------------- 2.6/16.5 MB 263.0 kB/s eta 0:00:53
   ------ --------------------------------- 2.6/16.5 MB 263.4 kB/s eta 0:00:53
   ------ --------------------------------- 2.6/16.5 MB 263.4 kB/s eta 0:00:53
   ------ --------------------------------- 2.6/16.5 MB 261.9 kB/s eta 0:00:53
   ------ --------------------------------- 2.7/16.5 MB 263.2 kB/s eta 0:00:53
   ------ --------------------------------- 2.7/16.5 MB 263.5 kB/s eta 0:00:53
   ------ --------------------------------- 2.7/16.5 MB 263.3 kB/s eta 0:00:53
   ------ --------------------------------- 2.7/16.5 MB 264.1 kB/s eta 0:00:53
   ------ --------------------------------- 2.7/16.5 MB 264.1 kB/s eta 0:00:53
   ------ --------------------------------- 2.7/16.5 MB 262.3 kB/s eta 0:00:53
   ------ --------------------------------- 2.7/16.5 MB 262.3 kB/s eta 0:00:53
   ------ --------------------------------- 2.7/16.5 MB 262.7 kB/s eta 0:00:53
   ------ --------------------------------- 2.8/16.5 MB 263.5 kB/s eta 0:00:53
   ------ --------------------------------- 2.8/16.5 MB 263.5 kB/s eta 0:00:53
   ------ --------------------------------- 2.8/16.5 MB 261.7 kB/s eta 0:00:53
   ------ --------------------------------- 2.8/16.5 MB 262.1 kB/s eta 0:00:53
   ------ --------------------------------- 2.8/16.5 MB 262.1 kB/s eta 0:00:53
   ------ --------------------------------- 2.8/16.5 MB 261.6 kB/s eta 0:00:53
   ------ --------------------------------- 2.8/16.5 MB 262.3 kB/s eta 0:00:53
   ------ --------------------------------- 2.8/16.5 MB 262.3 kB/s eta 0:00:53
   ------ --------------------------------- 2.8/16.5 MB 262.3 kB/s eta 0:00:53
   ------ --------------------------------- 2.9/16.5 MB 261.8 kB/s eta 0:00:53
   ------ --------------------------------- 2.9/16.5 MB 262.7 kB/s eta 0:00:52
   ------- -------------------------------- 2.9/16.5 MB 266.2 kB/s eta 0:00:51
   ------- -------------------------------- 3.0/16.5 MB 267.7 kB/s eta 0:00:51
   ------- -------------------------------- 3.0/16.5 MB 267.1 kB/s eta 0:00:51
   ------- -------------------------------- 3.0/16.5 MB 267.5 kB/s eta 0:00:51
   ------- -------------------------------- 3.0/16.5 MB 267.5 kB/s eta 0:00:51
   ------- -------------------------------- 3.0/16.5 MB 267.6 kB/s eta 0:00:51
   ------- -------------------------------- 3.1/16.5 MB 269.2 kB/s eta 0:00:51
   ------- -------------------------------- 3.1/16.5 MB 271.7 kB/s eta 0:00:50
   ------- -------------------------------- 3.1/16.5 MB 274.2 kB/s eta 0:00:49
   ------- -------------------------------- 3.2/16.5 MB 277.9 kB/s eta 0:00:48
   ------- -------------------------------- 3.2/16.5 MB 280.9 kB/s eta 0:00:48
   ------- -------------------------------- 3.3/16.5 MB 282.4 kB/s eta 0:00:47

In [4]:
#import mysql.connector

In [ ]:
#conn = mysql.connector.connect(host = 'localhost', user = 'root', password = 'Pk@dhfm5048', database = 'world')

In [3]:
#df = pd.read_sql_query('select * from city', conn)
#df

NameError: name 'conn' is not defined

In [3]:
#!pip uninstall mysql.connector -y

Found existing installation: mysql-connector 2.2.9
Uninstalling mysql-connector-2.2.9:
  Successfully uninstalled mysql-connector-2.2.9

In [4]:
#!pip uninstall mysql-connector -y

WARNING: Skipping mysql-connector as it is not installed.

In [5]:
#!pip uninstall mysql-connector-python -y

WARNING: Skipping mysql-connector-python as it is not installed.

In [6]:
#!pip install mysql_connector-python

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql_connector-python
  Downloading mysql_connector_python-9.6.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp312-cp312-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.5 MB 508.0 kB/s eta 0:00:32
   - -------------------------------------- 0.5/16.5 MB 508.0 kB/s eta 0:00:32
   - -------------------------------------- 0.5/16.5 MB 508.0 kB/s eta 0:00:32
   - -------------------------------------- 0.5/16.5 MB 508.0 kB/s eta 0:00:32
   - -------------------------------------- 0.5/16.5 MB 508.0 kB/s eta 0:00:32
   - -------------------------------------- 0.5/16.5 MB 508.0 kB/s eta 0:00:32
   - -------------------------------------- 0.8/16.5 MB 277.3 kB/s eta 0:00:57
   - -------------------------------------- 0.8/16.5 MB 277.3 kB/s eta 0:00:57
   - -------------------------------------- 0.8/16.5 MB 277.3 kB/s eta 0:00:57
   - -------------------------------------- 0.8/16.5 MB 277.3 kB/s eta 0:00:57
   - -------------------------------------- 0.8/16.5 MB 277.3 kB/s eta 0:00:57
   - -------------------------------------- 0.8/16.5 MB 277.3 kB/s eta 0:00:57
   -- ------------------------------------- 1.0/16.5 MB 247.9 kB/s eta 0:01:03
   -- ------------------------------------- 1.0/16.5 MB 247.9 kB/s eta 0:01:03
   -- ------------------------------------- 1.0/16.5 MB 247.9 kB/s eta 0:01:03
   -- ------------------------------------- 1.0/16.5 MB 247.9 kB/s eta 0:01:03
   --- ------------------------------------ 1.3/16.5 MB 260.1 kB/s eta 0:00:59
   --- ------------------------------------ 1.3/16.5 MB 260.1 kB/s eta 0:00:59
   --- ------------------------------------ 1.6/16.5 MB 295.3 kB/s eta 0:00:51
   --- ------------------------------------ 1.6/16.5 MB 295.3 kB/s eta 0:00:51
   --- ------------------------------------ 1.6/16.5 MB 295.3 kB/s eta 0:00:51
   --- ------------------------------------ 1.6/16.5 MB 295.3 kB/s eta 0:00:51
   --- ------------------------------------ 1.6/16.5 MB 295.3 kB/s eta 0:00:51
   ---- ----------------------------------- 1.8/16.5 MB 290.1 kB/s eta 0:00:51
   ---- ----------------------------------- 1.8/16.5 MB 290.1 kB/s eta 0:00:51
   ---- ----------------------------------- 1.8/16.5 MB 290.1 kB/s eta 0:00:51
   ---- ----------------------------------- 1.8/16.5 MB 290.1 kB/s eta 0:00:51
   ---- ----------------------------------- 1.8/16.5 MB 290.1 kB/s eta 0:00:51
   ----- ---------------------------------- 2.1/16.5 MB 281.6 kB/s eta 0:00:52
   ----- ---------------------------------- 2.1/16.5 MB 281.6 kB/s eta 0:00:52
   ----- ---------------------------------- 2.1/16.5 MB 281.6 kB/s eta 0:00:52
   ----- ---------------------------------- 2.1/16.5 MB 281.6 kB/s eta 0:00:52
   ----- ---------------------------------- 2.1/16.5 MB 281.6 kB/s eta 0:00:52
   ----- ---------------------------------- 2.4/16.5 MB 279.6 kB/s eta 0:00:51
   ----- ---------------------------------- 2.4/16.5 MB 279.6 kB/s eta 0:00:51
   ----- ---------------------------------- 2.4/16.5 MB 279.6 kB/s eta 0:00:51
   ----- ---------------------------------- 2.4/16.5 MB 279.6 kB/s eta 0:00:51
   ------ --------------------------------- 2.6/16.5 MB 286.0 kB/s eta 0:00:49
   ------ --------------------------------- 2.6/16.5 MB 286.0 kB/s eta 0:00:49
   ------ --------------------------------- 2.6/16.5 MB 286.0 kB/s eta 0:00:49
   ------ --------------------------------- 2.6/16.5 MB 286.0 kB/s eta 0:00:49
   ------ --------------------------------- 2.6/16.5 MB 286.0 kB/s eta 0:00:49
   ------ --------------------------------- 2.6/16.5 MB 286.0 kB/s eta 0:00:49
   ------ --------------------------------- 2.9/16.5 MB 275.5 kB/s eta 0:00:50
   ------ --------------------------------- 2.9/16.5 MB 275.5 kB/s eta 0:00:50
   ------- -------------------------------- 3.1/16.5 MB 287.0 kB/s eta 0:00:47
   ------- -------------------------------- 3.1/16.5 MB 287.0 kB/s eta 0:00:47
   ------- -------------------------------- 3.1/16.5 MB 287.0 kB/s eta 0:00:47
   ------- -------------------------------- 3.1/16.5 MB 287.0 kB/s eta 0:00:47
   ------- -------------------------------- 3.1/16.5 MB 287.0 kB/s eta 0:00:47
   ------- -------------------------------- 3.1/16.5 MB 287.0 kB/s eta 0:00:47
   ------- -------------------------------- 3.1/16.5 MB 287.0 kB/s eta 0:00:47
   ------- -------------------------------- 3.1/16.5 MB 287.0 kB/s eta 0:00:47
   -------- ------------------------------- 3.4/16.5 MB 270.2 kB/s eta 0:00:49
   -------- ------------------------------- 3.4/16.5 MB 270.2 kB/s eta 0:00:49
   -------- ------------------------------- 3.4/16.5 MB 270.2 kB/s eta 0:00:49
   -------- ------------------------------- 3.4/16.5 MB 270.2 kB/s eta 0:00:49
   -------- ------------------------------- 3.4/16.5 MB 270.2 kB/s eta 0:00:49
   -------- ------------------------------- 3.7/16.5 MB 268.6 kB/s eta 0:00:48
   -------- ------------------------------- 3.7/16.5 MB 268.6 kB/s eta 0:00:48
   -------- ------------------------------- 3.7/16.5 MB 268.6 kB/s eta 0:00:48
   -------- ------------------------------- 3.7/16.5 MB 268.6 kB/s eta 0:00:48
   -------- ------------------------------- 3.7/16.5 MB 268.6 kB/s eta 0:00:48
   --------- ------------------------------ 3.9/16.5 MB 266.0 kB/s eta 0:00:48
   --------- ------------------------------ 3.9/16.5 MB 266.0 kB/s eta 0:00:48
   --------- ------------------------------ 3.9/16.5 MB 266.0 kB/s eta 0:00:48
   --------- ------------------------------ 3.9/16.5 MB 266.0 kB/s eta 0:00:48
   --------- ------------------------------ 3.9/16.5 MB 266.0 kB/s eta 0:00:48
   --------- ------------------------------ 3.9/16.5 MB 266.0 kB/s eta 0:00:48
   ---------- ----------------------------- 4.2/16.5 MB 260.2 kB/s eta 0:00:48
   ---------- ----------------------------- 4.2/16.5 MB 260.2 kB/s eta 0:00:48
   ---------- ----------------------------- 4.2/16.5 MB 260.2 kB/s eta 0:00:48
   ---------- ----------------------------- 4.2/16.5 MB 260.2 kB/s eta 0:00:48
   ---------- ----------------------------- 4.2/16.5 MB 260.2 kB/s eta 0:00:48
   ---------- ----------------------------- 4.2/16.5 MB 260.2 kB/s eta 0:00:48
   ---------- ----------------------------- 4.5/16.5 MB 256.9 kB/s eta 0:00:47
   ---------- ----------------------------- 4.5/16.5 MB 256.9 kB/s eta 0:00:47
   ---------- ----------------------------- 4.5/16.5 MB 256.9 kB/s eta 0:00:47
   ---------- ----------------------------- 4.5/16.5 MB 256.9 kB/s eta 0:00:47
   ---------- ----------------------------- 4.5/16.5 MB 256.9 kB/s eta 0:00:47
   ---------- ----------------------------- 4.5/16.5 MB 256.9 kB/s eta 0:00:47
   ----------- ---------------------------- 4.7/16.5 MB 253.1 kB/s eta 0:00:47
   ----------- ---------------------------- 4.7/16.5 MB 253.1 kB/s eta 0:00:47
   ----------- ---------------------------- 4.7/16.5 MB 253.1 kB/s eta 0:00:47
   ----------- ---------------------------- 4.7/16.5 MB 253.1 kB/s eta 0:00:47
   ----------- ---------------------------- 4.7/16.5 MB 253.1 kB/s eta 0:00:47
   ----------- ---------------------------- 4.7/16.5 MB 253.1 kB/s eta 0:00:47
   ------------ --------------------------- 5.0/16.5 MB 250.2 kB/s eta 0:00:47
   ------------ --------------------------- 5.0/16.5 MB 250.2 kB/s eta 0:00:47
   ------------ --------------------------- 5.0/16.5 MB 250.2 kB/s eta 0:00:47
   ------------ --------------------------- 5.0/16.5 MB 250.2 kB/s eta 0:00:47
   ------------ --------------------------- 5.0/16.5 MB 250.2 kB/s eta 0:00:47
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------ --------------------------- 5.2/16.5 MB 249.0 kB/s eta 0:00:46
   ------------- -------------------------- 5.5/16.5 MB 221.8 kB/s eta 0:00:50
   ------------- -------------------------- 5.5/16.5 MB 221.8 kB/s eta 0:00:50
   ------------- -------------------------- 5.5/16.5 MB 221.8 kB/s eta 0:00:50
   ------------- -------------------------- 5.5/16.5 MB 221.8 kB/s eta 0:00:50
   ------------- -------------------------- 5.5/16.5 MB 221.8 kB/s eta 0:00:50
   ------------- -------------------------- 5.5/16.5 MB 221.8 kB/s eta 0:00:50
   ------------- -------------------------- 5.5/16.5 MB 221.8 kB/s eta 0:00:50
   ------------- -------------------------- 5.5/16.5 MB 221.8 kB/s eta 0:00:50
   ------------- -------------------------- 5.8/16.5 MB 217.3 kB/s eta 0:00:50
   ------------- -------------------------- 5.8/16.5 MB 217.3 kB/s eta 0:00:50
   ------------- -------------------------- 5.8/16.5 MB 217.3 kB/s eta 0:00:50
   ------------- -------------------------- 5.8/16.5 MB 217.3 kB/s eta 0:00:50
   ------------- -------------------------- 5.8/16.5 MB 217.3 kB/s eta 0:00:50
   ------------- -------------------------- 5.8/16.5 MB 217.3 kB/s eta 0:00:50
   -------------- ------------------------- 6.0/16.5 MB 217.2 kB/s eta 0:00:49
   -------------- ------------------------- 6.0/16.5 MB 217.2 kB/s eta 0:00:49
   -------------- ------------------------- 6.0/16.5 MB 217.2 kB/s eta 0:00:49
   --------------- ------------------------ 6.3/16.5 MB 220.7 kB/s eta 0:00:47
   --------------- ------------------------ 6.3/16.5 MB 220.7 kB/s eta 0:00:47
   --------------- ------------------------ 6.6/16.5 MB 226.7 kB/s eta 0:00:44
   --------------- ------------------------ 6.6/16.5 MB 226.7 kB/s eta 0:00:44
   --------------- ------------------------ 6.6/16.5 MB 226.7 kB/s eta 0:00:44
   --------------- ------------------------ 6.6/16.5 MB 226.7 kB/s eta 0:00:44
   --------------- ------------------------ 6.6/16.5 MB 226.7 kB/s eta 0:00:44
   --------------- ------------------------ 6.6/16.5 MB 226.7 kB/s eta 0:00:44
   --------------- ------------------------ 6.6/16.5 MB 226.7 kB/s eta 0:00:44
   --------------- ------------------------ 6.6/16.5 MB 226.7 kB/s eta 0:00:44
   --------------- ------------------------ 6.6/16.5 MB 226.7 kB/s eta 0:00:44
   ---------------- ----------------------- 6.8/16.5 MB 222.2 kB/s eta 0:00:44
   ---------------- ----------------------- 6.8/16.5 MB 222.2 kB/s eta 0:00:44
   ---------------- ----------------------- 6.8/16.5 MB 222.2 kB/s eta 0:00:44
   ---------------- ----------------------- 6.8/16.5 MB 222.2 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.1/16.5 MB 218.7 kB/s eta 0:00:44
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ----------------- ---------------------- 7.3/16.5 MB 214.9 kB/s eta 0:00:43
   ------------------ --------------------- 7.6/16.5 MB 187.0 kB/s eta 0:00:48
   ------------------ --------------------- 7.6/16.5 MB 187.0 kB/s eta 0:00:48
   ------------------ --------------------- 7.6/16.5 MB 187.0 kB/s eta 0:00:48
   ------------------ --------------------- 7.6/16.5 MB 187.0 kB/s eta 0:00:48
   ------------------- -------------------- 7.9/16.5 MB 188.5 kB/s eta 0:00:46
   ------------------- -------------------- 7.9/16.5 MB 188.5 kB/s eta 0:00:46
   ------------------- -------------------- 7.9/16.5 MB 188.5 kB/s eta 0:00:46
   ------------------- -------------------- 7.9/16.5 MB 188.5 kB/s eta 0:00:46
   ------------------- -------------------- 7.9/16.5 MB 188.5 kB/s eta 0:00:46
   ------------------- -------------------- 7.9/16.5 MB 188.5 kB/s eta 0:00:46
   ------------------- -------------------- 7.9/16.5 MB 188.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   ------------------- -------------------- 8.1/16.5 MB 183.5 kB/s eta 0:00:46
   -------------------- ------------------- 8.4/16.5 MB 174.6 kB/s eta 0:00:47
   -------------------- ------------------- 8.4/16.5 MB 174.6 kB/s eta 0:00:47
   -------------------- ------------------- 8.4/16.5 MB 174.6 kB/s eta 0:00:47
   -------------------- ------------------- 8.7/16.5 MB 178.8 kB/s eta 0:00:44
   -------------------- ------------------- 8.7/16.5 MB 178.8 kB/s eta 0:00:44
   -------------------- ------------------- 8.7/16.5 MB 178.8 kB/s eta 0:00:44
   -------------------- ------------------- 8.7/16.5 MB 178.8 kB/s eta 0:00:44
   -------------------- ------------------- 8.7/16.5 MB 178.8 kB/s eta 0:00:44
   -------------------- ------------------- 8.7/16.5 MB 178.8 kB/s eta 0:00:44
   --------------------- ------------------ 8.9/16.5 MB 177.3 kB/s eta 0:00:43
   --------------------- ------------------ 8.9/16.5 MB 177.3 kB/s eta 0:00:43
   --------------------- ------------------ 8.9/16.5 MB 177.3 kB/s eta 0:00:43
   --------------------- ------------------ 8.9/16.5 MB 177.3 kB/s eta 0:00:43
   --------------------- ------------------ 8.9/16.5 MB 177.3 kB/s eta 0:00:43
   --------------------- ------------------ 8.9/16.5 MB 177.3 kB/s eta 0:00:43
   --------------------- ------------------ 8.9/16.5 MB 177.3 kB/s eta 0:00:43
   ---------------------- ----------------- 9.2/16.5 MB 175.4 kB/s eta 0:00:42
   ---------------------- ----------------- 9.2/16.5 MB 175.4 kB/s eta 0:00:42
   ---------------------- ----------------- 9.2/16.5 MB 175.4 kB/s eta 0:00:42
   ---------------------- ----------------- 9.2/16.5 MB 175.4 kB/s eta 0:00:42
   ---------------------- ----------------- 9.2/16.5 MB 175.4 kB/s eta 0:00:42
   ---------------------- ----------------- 9.4/16.5 MB 176.6 kB/s eta 0:00:41
   ---------------------- ----------------- 9.4/16.5 MB 176.6 kB/s eta 0:00:41
   ---------------------- ----------------- 9.4/16.5 MB 176.6 kB/s eta 0:00:41
   ---------------------- ----------------- 9.4/16.5 MB 176.6 kB/s eta 0:00:41
   ---------------------- ----------------- 9.4/16.5 MB 176.6 kB/s eta 0:00:41
   ---------------------- ----------------- 9.4/16.5 MB 176.6 kB/s eta 0:00:41
   ---------------------- ----------------- 9.4/16.5 MB 176.6 kB/s eta 0:00:41
   ----------------------- ---------------- 9.7/16.5 MB 175.2 kB/s eta 0:00:39
   ----------------------- ---------------- 9.7/16.5 MB 175.2 kB/s eta 0:00:39
   ----------------------- ---------------- 9.7/16.5 MB 175.2 kB/s eta 0:00:39
   ----------------------- ---------------- 9.7/16.5 MB 175.2 kB/s eta 0:00:39
   ----------------------- ---------------- 9.7/16.5 MB 175.2 kB/s eta 0:00:39
   ----------------------- ---------------- 9.7/16.5 MB 175.2 kB/s eta 0:00:39
   ----------------------- ---------------- 9.7/16.5 MB 175.2 kB/s eta 0:00:39
   ------------------------ --------------- 10.0/16.5 MB 173.1 kB/s eta 0:00:38
   ------------------------ --------------- 10.0/16.5 MB 173.1 kB/s eta 0:00:38
   ------------------------ --------------- 10.0/16.5 MB 173.1 kB/s eta 0:00:38
   ------------------------ --------------- 10.0/16.5 MB 173.1 kB/s eta 0:00:38
   ------------------------ --------------- 10.0/16.5 MB 173.1 kB/s eta 0:00:38
   ------------------------ --------------- 10.2/16.5 MB 175.6 kB/s eta 0:00:36
   ------------------------ --------------- 10.2/16.5 MB 175.6 kB/s eta 0:00:36
   ------------------------ --------------- 10.2/16.5 MB 175.6 kB/s eta 0:00:36
   ------------------------ --------------- 10.2/16.5 MB 175.6 kB/s eta 0:00:36
   ------------------------ --------------- 10.2/16.5 MB 175.6 kB/s eta 0:00:36
   ------------------------ --------------- 10.2/16.5 MB 175.6 kB/s eta 0:00:36
   ------------------------ --------------- 10.2/16.5 MB 175.6 kB/s eta 0:00:36
   ------------------------ --------------- 10.2/16.5 MB 175.6 kB/s eta 0:00:36
   ------------------------- -------------- 10.5/16.5 MB 186.9 kB/s eta 0:00:33
   ------------------------- -------------- 10.5/16.5 MB 186.9 kB/s eta 0:00:33
   ------------------------- -------------- 10.5/16.5 MB 186.9 kB/s eta 0:00:33
   ------------------------- -------------- 10.5/16.5 MB 186.9 kB/s eta 0:00:33

In [2]:
import mysql.connector
print('success')

success

In [ ]:
conn = mysql.connector.connect(host = '127.0.0.1', user = 'root', password = 'Pk@dhfm5048', auth_plugin = 'caching_sha2_password')
print('connected')